version: "3.9"
services:
  lisandes:
    build: .
    image: cwds/lisandes
    volumes:
      - ./config/elasticsearch.yml:/elasticsearch.yml
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RUN_ENV: ${env-name}
