version: "3.9"
services:
  lisandes:
    build: .
    image: lisandes
    volumes:
      - ./config/elasticsearch.yml:/elasticsearch.yml
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
